# Generated by Django 3.2.20 on 2024-01-31 08:38

import bkuser.apps.tenant.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20240125_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='previous_status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('expired', '已过期'), ('deleted', '软删除')], default=bkuser.apps.tenant.constants.TenantUserStatus['ENABLED'], max_length=32, verbose_name='上一次状态'),
        ),
    ]
