# Generated by Django 3.2.20 on 2024-01-31 08:38

import bkuser.apps.data_source.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0007_auto_20240124_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceuser',
            name='previous_status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('deleted', '软删除')], default=bkuser.apps.data_source.constants.DataSourceUserStatus['ENABLED'], max_length=32, verbose_name='上一次状态'),
        ),
    ]
