# Generated by Django 3.2.20 on 2024-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0008_datasourceuser_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceuser',
            name='creator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datasourceuser',
            name='updater',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
